/**
 * DEF: CALCULA A FREQUENCIA DOS ELEMENTOS NO ARQUIVO
 *
 * @param f --- ARQUIVO A TER SEUS ELEMENTOS CONTADOS
 * @return INT --- RETORNA UMA LISTA COM A QUANTIDADE DE CADA ELEMENTO
 */
int *freq_w(FILE *f);
